name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - master  # Ensure this is your correct branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Ensure submodules (theme) are pulled

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build the site
        run: hugo --minify --gc --cleanDestinationDir

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAT }}  # Using Personal Access Token
          publish_dir: ./public
          publish_branch: gh-pages
          keep_files: false
          cname: ""

